### ISSUE TITLE
Expand README

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab-celltags#141]
...with a brief description of what exactly `jupyterlab-celltags` does.

**Comment by vidartf** [comment]
It would be nice with a screenshot to demonstrate what it looks like 👍

**Comment by dhirschfeld** [comment]
That would certainly help! I guess I'm confused about what it's relationship is to the [Cell Tools Inspector](https://github.com/jupyterlab/jupyterlab/issues/4100#issuecomment-370866626) - does it provide functionality over and above that or is it something completely different?

*Aside:* That link to a random issue comment was the best description I could find what the cell tools inspector actually was.

**Comment by vidartf** [comment]
I think this is a lot better now :)

**Comment by dhirschfeld** [comment]
Fixed by #154!
