### ISSUE TITLE
Check if tags are an array

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab-celltags#171]
The cell `"tags"` field should be an array of strings. However, the user can put any data in the cell metadata. When I was testing this, I accidentally put a string in the tags field, e.g.
```json
{
  "tags": "mytag"
}
```
and found that I got tags for "m", "y", "t", "a", and "g". We should do some validation on the tag values.

**Comment by markellekelly** [comment]
Fixed in #175, thanks for catching this!

**Comment by ian-r-rose** [comment]
Thanks!
