### ISSUE TITLE
Broken in JupyterLab 0.34.12

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/jupyterlab-celltags#174]
`@jupyterlab/celltags v0.1.4  enabled  OK`

![error](https://user-images.githubusercontent.com/1248413/46572026-36a6ea80-c977-11e8-99f8-3704b1c1bff6.png)

**Comment by mlenda** [comment]
👍

**Comment by markellekelly** [comment]
Fixed for JupyterLab 1.0 in #180.
