### ISSUE TITLE
Select all cells with this tag option not available

### ISSUE THREAD

**Issue by sudarshan85** [jupyterlab/jupyterlab-celltags#178]
Hi,

I'm running Jupyterlab version 0.35.2 and I think the latest extension version (I'm not sure how to check that). However, I don't see an option to "select all cells with this tag" option is not available for me. Any ideas?

**Comment by markellekelly** [comment]
The selection feature was relocated to the tag dropdown in the table of contents, but is in the process of being moved back right now. It should be back in cell tags within the next week or so!

**Comment by Cait-Doogan** [comment]
Hi, 
I'm looking forward to using this extension. Do you know when this issue will be resolved?
Thanks

**Comment by markellekelly** [comment]
The "select all" feature is available now in the new version of celltags, which works with JL 1.0 and above. Thanks!
