### ISSUE TITLE
Absob into lab core?

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab-celltags#179]
A cell tags UI is present in jupyter notebook by default, and I would argue that it would make sense for it to be present in lab by default as well. Are there any plans to merge this extension into jupyterlab core at some point? Are there any good arguments for not merging, or delaying it further?

**Comment by Zsailer** [comment]
@vidartf I'm not aware of any plans to merge into core, but I think it's a great idea.

We need to fix a few dependency installation issues in preparation for Jlab-1.0. We should have those fixed by the end of the week. 

Then, maybe we should bring this up at the next JLab meeting?

**Comment by vidartf** [comment]
> Then, maybe we should bring this up at the next JLab meeting?

Sounds like a good place to air the idea!

**Comment by rahulpshah** [comment]
Any update on this?

**Comment by BoPeng** [comment]
I think @vidartf should create a PR to make it a click away to merge this to the core.

**Comment by vidartf** [comment]
@zuoyuanh is the main author here, so therefore the best candidate to open the PR (also, the person that can say that they would prefer to keep the extension separate). Especially since @zuoyuanh is the most qualified to address any questions that would come up during the review. However, if the author is no longer working on this, I could possibly adopt it, but I feel like I already have enough to do 😅

**Comment by Zsailer** [comment]
@markellekelly has been maintaining cell-tags recently (she's a Jupyter Intern at Cal Poly). She recently made a big push to add docstrings, fix CSS issues, and make compatible with JLab v1.0. 

She is on vacation for the next two weeks. I'll work with her when she returns and submit a PR to Jupyterlab core sometime over the summer. 

Also, FYI—@zuoyuanh just finished his internship and likely won't be working on this anymore.

**Comment by ellisonbg** [comment]
Sounds good, thanks @markellekelly and @Zsailer !

**Comment by vidartf** [comment]
Just thought I should ping this. Ideally this should have been in for lab 1.0 w.r.t. feature parity with classic notebook.

**Comment by gavinmh** [comment]
Any updates?

**Comment by vidartf** [comment]
I think everyone is agreed that this is something that should be done (merging into core). I think the step that is missing is someone actually doing the legwork (opening a PR to core).

**Comment by vidartf** [comment]
PS: Anybody who wants to help with the legwork are very welcome to do so!

**Comment by telamonian** [comment]
There's already a couple of Cal Poly interns working on this. See #199. Their plan is to refactor `celltags` more-or-less from the ground up (using Phosphor widgets in place of React components) and then get the redesigned version merged into core once its done. The ongoing work is at https://github.com/markellekelly/celltags.

Personally, I somewhat question the need for both the replacement of the components and the refactor in general, but so long as it gets done in the end I suppose it's fine.

**Comment by vidartf** [comment]
Ah, sorry for missing the other issues. Consider that the authoritative answer then 👍

**Comment by h-vetinari** [comment]
@telamonian @vidartf 
Why not absorb into core first and *then* refactor? That way, if the refactor takes longer than expected for any reason, the core would not have to wait X weeks/months until celltags become available.

**Comment by vidartf** [comment]
@h-vetinari I don't know this codebase very well, so if the people who do say that they want to do a refactor first, I'm going to assume they have a reason 😃

**Comment by h-vetinari** [comment]
Since there are no GH-pings for issues being referred to, I was just very positively surprised while reading the JLab 2.0 [release notes](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html) that this issue has been solved (see jupyterlab/jupyterlab#7407). Great work, thanks! :)
