### ISSUE TITLE
CellTags not visible after install

### ISSUE THREAD

**Issue by mudomau** [jupyterlab/jupyterlab-celltags#186]
I've tried installing celltags using the method described. 

I can see it in the Extension Manager as installed and enabled, but when I go to the Cell Inspector, I dont see any Tags option. I'm also unable to manually input metadata.

Using JupyterLab 0.35.4 through Anaconda.

Any ideas what the issue could be?

![image](https://user-images.githubusercontent.com/2564029/60606928-86a6c680-9dbc-11e9-84bc-7ac64e42b93e.png)

![image](https://user-images.githubusercontent.com/2564029/60606959-97efd300-9dbc-11e9-95e6-fe5fd5414b29.png)

**Comment by e01n0** [comment]
same here - using lab version 0.35.4

**Comment by hoangthienan95** [comment]
Maybe because they updated to 1.0.0?

```
[W 18:00:29.735 LabApp] Incompatible extension:
    
    "@jupyterlab/celltags@0.1.5" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension        Package
    >=0.19.1 <0.20.0        >=1.0.0-alpha.6 <2.0.0@jupyterlab/application
    >=0.19.1 <0.20.0        >=1.0.0-alpha.6 <2.0.0@jupyterlab/apputils
    >=0.19.1 <0.20.0        >=1.0.0-alpha.6 <2.0.0@jupyterlab/docmanager
    >=0.19.2 <0.20.0        >=1.0.0-alpha.6 <2.0.0@jupyterlab/notebook
    >=0.19.1 <0.20.0        >=1.0.0-alpha.6 <2.0.0@jupyterlab/rendermime
    
[W 18:00:29.736 LabApp] Found compatible version: 0.1.4
[I 18:00:29.736 LabApp] > /lab/corradin_data/FOR_AN/anaconda3/bin/npm pack @jupyterlab/celltags@0.1.4
```

**Comment by mudomau** [comment]
Probabbly - I updated to Jlab 1.0 and CellTags is available now.
