### ISSUE TITLE
Icons are not rendered correctly

### ISSUE THREAD

**Issue by jebovic** [jupyterlab/jupyterlab-celltags#194]
Hi,
I'm trying to install the extension on the last version of jupyterlab (v1.1.1).
As you can see on the screenshot below, icons are not rendered anymore.

![image](https://user-images.githubusercontent.com/1228464/64361313-93d67080-d00c-11e9-8c86-ea0956e3b672.png)

After investigation, it seems that the upgrade of babel from version 5 to 6 is responsible of this issue. It's certainly updated in the dependency tree of other packages and extensions in the Jupyter environment.

The require function behavior has changed, and the call to the "require" function (here: https://github.com/jupyterlab/jupyterlab-celltags/blob/master/src/components/tag.tsx#L117) now returns an object, and not a string as expected.

From web browser :

![image](https://user-images.githubusercontent.com/1228464/64362113-33e0c980-d00e-11e9-8827-9533d6a6b6a5.png)

From the code, this call returns an object :
`src={require('../../static/add_blue.svg')}`

The fix which returns what's expected for a src attribute :
`src={require('../../static/add_blue.svg').default}`

Another solution would be to use this plugin : https://www.npmjs.com/package/babel-plugin-add-module-exports

Regards,
Jérémy

**Comment by choldgraf** [comment]
I've got the same issue!

**Comment by timkpaine** [comment]
its widespread :-(

**Comment by choldgraf** [comment]
@timkpaine ah that's a bummer :-/  I wonder if this is a good opportunity for someone to write a short Discourse post on what the problem is so that other extension developers can discover the fix? I assume it's the same problem across all of them (and I'm guessing it's some kind of dependency version bump issue?)

**Comment by blink1073** [comment]
@telamonian, I think this is related to https://github.com/jupyterlab/jupyterlab/pull/6034, mind taking a look?  It says "Could not load the image" when I hover over the image src below:

![image](https://user-images.githubusercontent.com/2096628/64474269-abab1300-d138-11e9-85d3-22ee79b6e71b.png)

**Comment by telamonian** [comment]
@blink1073 This is an alternative means of inlining SVGs than what I worked on. I'm not super familiar with the `require` function or with `babel`, so I can't comment on what broke.

The problem could potentially be fixed using some of the machinery that jupyterlab/jupyterlab#6034 adds. The best way to expose said machinery to external extensions hasn't really been worked out, but this could be a chance to do so. I'll look into it.

**Comment by choldgraf** [comment]
It seemed from the comments in this thread that all we had to do was add `default` to the image calls, so I did that in

**Comment by DancingQuanta** [comment]
I have this issue too!

**Comment by telamonian** [comment]
I figured out exactly why this bug happened when it happened. In Jupyterlab `v1.1`, in the build system, the Webpack loader for `.svg` files changed from `url-loader` to `raw-loader`. The loader determines the details of the implementation of the `require` function. For the `url-loader`, this statement:

```typescript
require('<path-to-svg>/foo.svg')
```

used to return a string, but for the `raw-loader` it returns a module object. The `.default` property of that module object is a string with the raw contents of the imported `.svg`. That's why you now have to add the `.default` to get the import to work correctly.

**Comment by rftw** [comment]
> 
> 
> I figured out exactly why this bug happened when it happened. In Jupyterlab `v1.1`, in the build system, the Webpack loader for `.svg` files changed from `url-loader` to `raw-loader`. The loader determines the details of the implementation of the `require` function. For the `url-loader`, this statement:
> 
> ```ts
> require('<path-to-svg>/foo.svg')
> ```
> 
> used to return a string, but for the `raw-loader` it returns a module object. The `.default` property of that module object is a string with the raw contents of the imported `.svg`. That's why you now have to add the `.default` to get the import to work correctly.

How can I install the new version of cell tags? I tried installing jupyterlab and jupyterlab/celltags but the icons are still not rendering properly

**Comment by telamonian** [comment]
@rtfw A new release (`v0.2.0`) of `@jupyterlab/celltags` has now been published that includes the fixes for this issue. If you uninstall/reinstall celltags, it should now be fixed for you

**Comment by choldgraf** [comment]
It worked for me, hooray!

**Comment by rftw** [comment]
Yup! working now. Thank you for fixing it

**Comment by telamonian** [comment]
Glad to hear it. One nice side effect of prepping a new release was that I also cleared out this repo's PR backlog!

**Comment by Zsailer** [comment]
This is awesome, thanks @telamonian!
